export * from './Footer/footer'
export * from './Searchbar/searchbar';
export * from './ActorCard/actor-card';
export * from './Slider/slides';
export * from './Sidemenu/sidemenu';
export * from './BottomNavbar/bottom-nav';
export * from './SimilarMovies/similar-movies';
export * from './BackButton/back-button';
export * from './ReviewCard/review-card';
export * from './Modal/modal';
export * from './SecondHeader/second-header';